name: drm-bot-2
routes:
  - name: main
    src: http
    dest: http
services:
  - name: drm-bot-2
    image:
      name: docker.io/library/drm-bot-2
      tag: latest
    ports:
      - port: 80
        protocol: http
    env:
      - name: API_ID
        value: "27743952"
      - name: API_HASH
        value: "416ba062bd16c6cf1aa38dd389726023"
      - name: BOT_TOKEN
        value: "7854261395:AAGFoRKyb7Xlx1TTOEpwuR5A3H-tnYLmdPo"
